site_name: Vinum
repo_name: Plothan/Vinum
repo_url: https://github.com/Plothan/Vinum

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
extra_css:
  - stylesheets/theme.css
nav:
  - Home: index.md
  - Tutorials:
    - Get Started: Tutorials/index.md
    - Fundamental:
      - State Holding: Tutorials/fundamental/hold.md
      - State Observing: Tutorials/fundamental/observe.md
      - State Calculating: Tutorials/fundamental/calc.md
      - Processors: Tutorials/fundamental/proc.md
    - Advanced:
      - State Matching: Tutorials/advanced/match.md
      - State Grouping: Tutorials/advanced/group.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
