[package]
name = "sinlerdev/vinum"
version = "0.2.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "A multi-paradigm, fast and modern reactive state management library."
include = ["src", "default.project.json"]

[dependencies]
